GetDKAN/dkan-tools

bin/dktl.sh

Fixes #6
**QA**
- dktl dc up -d
- dktl (composer install should run)
- dktl (composer should not run again)

Runs composer install inside of the cli container if the vendor directory does not exist.

---

README.md
bin/dktl.sh

Connects #10 
**QA**
- Try `dktl dkan:get`, chown should happen
- Create the environment variable `export DKTL_CHOWN="FALSE"`, chown should not happen
- Modify variable `export DKTL_CHOWN="TRUE"`, chown should happen again

Make chown behavior optional

---

src/Command/BasicCommands.php

Fixes a bug that appeared on a `dktl init` command, where namespacing for `Result` class was ambiguous.

Use Robo/Result to eliminate ambiguity

---

bin/dktl.sh
composer.json
composer.lock
src/Command/BasicCommands.php
src/Command/DkanCommands.php
src/Command/TestCommands.php

Connects #13
**QA**
- Run `dktl phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info /var/www/dkan/modules/dkan/<some_module>`
- If you want to fix some of the issues, run `dktl phpcbf --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info /var/www/dkan/modules/dkan/<some_module>`
- Run `dktl test:lint dkan/modules/dkan/dkan_datastore dkan/modules/dkan/dkan_dataset`
- Run `dktl test:lint-fix dkan/modules/dkan/dkan_datastore dkan/modules/dkan/dkan_dataset`

Adding basic linting.

---

assets/docker/docker-compose.common.yml
src/Command/DkanCommands.php

Also adds a tweak to the restore command to make arguments optional. This lets me, for instance, comment out one of the arguments from my dktl.yml file to skip the files restore, without having to change DKTL code if I want to skip that for now.

Switch to php7-web container

---

assets/.probo.yml
src/Command/TestCommands.php

Fixes #62 
This creates a new command `dktl test:qa-users`, which creates the three QA users (creator, editor and sitemanager) we used to get with ahoy. It additionally accepts a `-w`/`--workflow` option that will check to see if dkan_workflow_permissions is enabled, and if so, add three more users with the Workflow-specific roles.
1. Create a fresh DKAN site with this branch of DKTL
2. Try `dktl test:qa-users` and confirm that the three users are created and you can log in as expected.
3. Reset the DB to its initial state with `dktl dkan:install -b`.
4. Try `dktl tes:qa-users -w` and confirm that it refuses to proceed
5. Enable dkan_workflow_permissions and its dependencies: `dktl dkan en -y dkan_workflow_permissions`
6. Try `dktl tes:qa-users -w` and confirm that it creates all six …

Add QA users command

---

src/Command/RestoreCommands.php

I'm not sure why this suddenly started breaking but have been getting errors because the path was ambiguous.

Add trailing slash to aws cp command

---

bin/dktl

Without `-f`, the dktl command will not detect the true location of the dkan-tools root directory correctly and the docker command will fail (looking for docker-compose.common.yml in the wrong place). This ensures that `$DKTL_DIRECTORY` is an absolute path.
From the `readlink` man:
> **-f, --canonicalize**
>>    canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist 
1. Check out the branch, and make sure the `dktl` command works from any subdir of the project.
2. For full QA, do something like what I have set up for my dktl path: install dkan-tools at _~/Work/dkan-tools_ (or a similar path in your home), add a symlink to _~/Work/dkan-tools/bin in ~/.local/bin (and make sure the latter is in your `$PATH`). 
3. Try …

Add -f to readlink command to get correct $DKTL_DIRECTORY

---

bin/dktl

Previously the `-f` option was added to a `readlink` command in the dktl script to better support symlinks to the script. The problem however is that `readlink` w/o options in Mac behaves more like `readlink -f` in linux. This change should address both platforms.
On my system, dkan-tools lives at _~/Work/dkan-tools_, so the actual script is at _~/Work/dkan_tools/bin/dktl_, but the symlink lives at _~/.local/bin_. In other words, 
```
$ which dktl
/home/dfeder/.local/bin/dktl
$ ls -la /home/dfeder/.local/bin/dktl
lrwxrwxrwx 1 dfeder dfeder 30 Feb  4 07:11 /home/dfeder/.local/bin/dktl -> ../../Work/dkan-tools/bin/dktl
```

Only apply -f option to readlink on linux

---

src/Drupal/V7/DkanCommands.php
src/Drupal/V7/MakeCommands.php

1. `dktl dkan:get` would still try to proceed even if version was not available.
2. `dktl make` would proceed to Drupal make even if DKAN make failed due to bad yaml.

Fix some minor error handling issues with make and dkan:get

---

bin/dktl
src/Command/DockerCommands.php

Clean up the url and uri commands a bit. While the old ones are still suported, we now have:
`dktl surl` - the secure url for the current dktl project
`dktl url` - the insecure url for the current dktl project
`dktl suli` - open a password reset link (`drush uli`) with the correct secure url
`dktl uli` - open a password reset link (`drush uli`) with the correct insecure url
I considered the possibility of just having `url/uli` and using the secure url there, since personally I have no use for the insecure url and don't see any utility for having it available. But I opted for this to be on the safe side. LMK if you think I should have gone with that option.

Cleanup url and add uli commands

---

bin/dktl

If DKTL_NO_PTY is set, always pass -T to docker compose exec to make sure no pty is allocated.   Thi seems to help with running dktl in some CI pipelines, such as CircleCI.
Connects GetDKAN/dkan-tools#14

Docker compose error

---

src/Command/TestCommands.php

This lets us override the check for the presence of `dkan_workflow_permissions` before running `dktl test:qa-users --workflow`. This is required for a project where we have the same workflow role names but using a custom module.
* Start with a site w/o dkan_workflow_permissions
* Create roles "Workflow Supervisor", "Workflow Moderator" and "Workflow Contributor"
* Run `dktl test:qa-users -w -y`. It should create six QA users.

Add -y option to testQAUsers

---

assets/d8/site/settings.php
assets/docker/docker-compose.common.yml
src/Drupal/V8/InitCommands.php
src/Util/Util.php

This PR contains a few improvements that apply to D8 sites:
1) Set `DKTL_DOCKER=1` in web container
1) Add hash salt to `settings.php` during `dktl init`
1) Define config sync directory in `settings.php` (the sync directory is created automatically during the Drupal/DKAN installation).

Add hash salt and config sync directory to settings.php

---

README.md
assets/docker/docker-compose.common.yml
src/Command/BasicCommands.php

Connects https://github.com/getdkan/dkan/issues/2822
Added command for creating a database backup excluding cache, devel, webform submissions and DKAN datastore tables. This command works fine just when it is run on DKTL_MODE set to HOST because otherwise the drush aliases are not passed to the docker containers and even when we do that we get issues because of ssh/config owners and permissions.

Database backup excluding tables

---

README.md
assets/test/behat.docker.yml
assets/test/behat.yml
assets/test/features/bootstrap/FeatureContext.php
assets/test/phpunit/boot.php
assets/test/phpunit/example/CustomTest.php
assets/test/phpunit/phpunit.xml
src/Drupal/V7/InitCommands.php
src/Util/Util.php

To make sure we have an easy way to set up custom tests, this adds a `dktl init:custom-tests` command to dkan-tools, which sets up the scaffolding of a custom test suite. It is also now included in a standard `dktl init` command.
1. Start a new dktl project, build and install DKAN
2. Try the `dktl test:behat-custom` and `dktl test:phpunit-custom` commands.

Automatically set up custom tests on project

---

src/Util/Util.php

It seems like we might want to actually throw an exception rather than just some output when the init commands fail to create files. But I may be forgetting why we wrote that Util method that way in the first place. Thoughts @fmizzell ?

Use exception instead of just io() error on file check

---

README.md

Change `dtkl` to `dktl` in the README's Xdebug command.

Fix typo in xdebug command

---

src/Drupal/V7/InitCommands.php
src/Drupal/V8/BasicCommands.php

If running `dktl make --frontend`, the command will now provide this warning at the end of the make:
It also adds a new `--frontend` switch to `install` to enable the dkan_frontend module manually.
Some code styling improvements are also included.

Warning on install command if building frontend

---

bin/dktl

All `dktl` commands for me on a certain project were ending output with:
```
/home/██████/local/bin/dktl: line 145: [: too many arguments
```
I realized it was because the find command on that line was returning filenames with spaces in them, which were not being escaped in any way. Wrapping the whole expression in quotes prevents this. 
1. With current dkan-tools master, run `dktl dc exec cli bash`
2. Go to the project root (/var/www) 
3. Create two files with a space in the file name: `touch 'file 1' && touch 'file 1'`
4. `exit`
5. Run `dktl` and see the "too many arguments" error
1. Check out this branch
2. Go to the project root (/var/www) 
3. Create two files with a space in the file name: `touch 'file 1' && touch 'file 1'`
4. `exit`
5. Run `dktl` and confirm no "too many arguments" …

Quote find command in chown

---

src/Drupal/V7/MakeCommands.php

MakeCommands::makeProfile return a bool or a Robo\Result object which error off the
calling MakeCommands::make function with "Call to a member function
getExitCode() on bool".
PR to unify the return type from `MakeCommands::makeProfile`
To QA, just run `dktl make` and no to `DKAN dependencies have already been dowloaded. Would you like to delete and dowload them again? (yes/no)`

Fix inconsistent return from MakeCommands::makeProfile

---

src/Drupal/V7/MakeCommands.php

Added new command to patch dkan.

---

README.md
assets/docker/docker-compose.common.yml

Github throws a fit through composer some times. 
When that happens it asks you to create a token. 
That token is placed in a directory in the user's profile. 
This PR shares that directory from the host machine into the CLI container, so the token is set once and available every time the container runs composer.

Adding the host's config related to composer to the containers.

---

assets/d8/composer.json
src/Command/BasicCommands.php
src/Command/DkanCommands.php
tests/DktlTest.php

Temporary "pseudo profile" drush steps added to enable modules and adjust config so there are not burdensome manual steps for standing up an OOB site.
connected to https://github.com/GetDKAN/dkan2/compare/359-deprofiling

Create configuration profile-like module for fresh d8 install

---

src/Command/BasicCommands.php

Use-cases:
1. Installing from an existing config, might as well bypass the installation and default modules
2. Users may not be using the Standard installation profile

Allow installation from existing config

---

README.md
src/Command/BasicCommands.php
src/Command/FrontendCommands.php
src/Command/InstallCommands.php

This allows users to build DKAN with the frontend using a specific branch of data-catalog-frontend.

Support flag --frontend-build on make command

---

README.md
src/Command/InstallCommands.php

Support flag --demo-backend on install command

---

src/Command/InitCommands.php
src/Command/InstallCommands.php

see #201 
- stand up a dkan2 site so that you have a `/src` directory
- run `dktl make` again, confirm you do not get the `Could not delete /var/www/docroot/sites/default/default.services.yml:` error

Reset permissions when re-using containers

---

src/Command/DockerCommands.php

Getting PHP error when running `dktl uli` with DKTL_MODE set to 'HOST'. I suspect this is due to the PHP being version 7.2.
This is a small patch to show the exception message correctly.

fix PHP Warning for undefined constant DKTL_DOCKER_PHP_ERROR

---

src/Drupal/V7/MakeCommands.php

Not sure how this wasn't noticed till now, but recent push to fix code style issues broke one of the link functions in the 1.x make command. Just some silly mistakes.

Fix mistakes in refactored make command

---

src/Command/FrontendCommands.php
src/Command/InstallCommands.php

I'm able to consistently reproduce the following error running `dktl install --frontend` 
`Unable to install modules dkan_frontend due to missing modules dkan_frontend.`
Looking at the new dkan code, it seems like the wanted Dkan module name is `frontend`, not `dkan_frontend`.
Using the correct name fixes the issue:

DKAN Frontend module name is `frontend`

---

assets/script/deploy.sh

`dktl deploy <env>` does not work with dkan2. Most of the steps are Drupal 7 specific or require features that are not in dkan2 (yet?).
This PR cleans up the `deploy.sh` script to the simplest list of commands needed to re-deploy a dkan2 instance.
Also small tweak to make the script more readable, and fix couple warnings raised by [shellcheck](https://www.shellcheck.net/) (variable quoting).

Make deploy script work with dkan2 instances

---

assets/docker/docker-compose.common.yml

Stop using a host volume for composer to avoid collisions with host environment
1. Check out this branch in your local dkan-tools
2. Create a dkan2 project
3. Some times during make, composer will ask you to create a github token to overcome rate limiting.
4. Create new dkan projects
Composer should not ask for tokens again, as they should persist.

Remove database_data volume and add composer

---

assets/docker/docker-compose.common.yml

Currently, the dkan-tools sources the AWS credentials by
1. Reading credentials directly from environment variables (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY).
2. Mounting `~/.aws` directory, and sourcing the default AWS profile set.
When having no default AWS profile, we can't connect to S3 except by setting the credentials env variables, despite those being already available in the `~/.aws` directory.
With this change, we can use the standard AWS cli way of specifying which profile to load using the `AWS_PROFILE` env variable from the host.

Support AWS_PROFILE environment variable (1.x)

---

assets/docker/docker-compose.common.yml

Since we already mount the `~/.aws` directory onto the container. We can simply set the `AWS_PROFILE` variable in the host to make the AWS commands work.

Support AWS_PROFILE env variable

---

assets/docker/docker-compose.common.yml

connects NuCivic/dkan_management#338
connects GetDKAN/dkan2#366
Requires https://github.com/GetDKAN/dkan-cli/pull/1
Requires https://hub.docker.com/repository/docker/getdkan/dkan-web/tags have `latest` tag.
Requires https://hub.docker.com/repository/docker/getdkan/dkan-cli/tags have `classic` tag.
Use new Dkan specific docker images with PHP 7.3 Supports

1.x - Use new images with PHP 7.3 support

---

.circleci/config.yml
src/Command/TestCommands.php

This adds a command `dktl test:dktl` to run DKTL's own internal test suite, and runs it in CircleCI.
Not sure that's really the right place for such a command; open to other suggestions.
- Tests on this PR should execute and fail
- Commit status should show failed due to tests (not another build error)

Add command for DKTL self-testing

---

src/Command/DkanCommands.php

Fixes GetDKAN/dkan-catalog-frontend#57
When comparing urls in the frontend we are building using `$DKTL_PROXY_DOMAIN` but the Cypress tests set the base url to web. This causes the dataset file download test to fail as `web` does not match with `sandbox.localtest.me` in the Gatsby code.  
QA:
In a DKAN instance
1. `dktl make --frontend=cypress-updates-07-24` This branch has passing tests for the Gatsby build.
1. `dktl install --demo` The data used for the frontend Cypress tests.
1. `dktl drush user:create testuser --password="2jqzOAnXS9mmcLasy"` Users needed for backend Cypress tests.
1. `dktl drush user-add-role api_user testuser`
1. `dktl drush user:create testeditor --password="testeditor"`
1. `dktl drush user-add-role administrator testeditor`
1. `dktl dkan:test-cypress` Test Cypress …

Change Cypress base url from web to $DKTL_PROXY_DOMAIN

---

src/DrupalProjectTrait.php

Fixes: https://github.com/GetDKAN/dkan-tools/issues/259
On an existing dktl project. Running `dktl init` should ask before overriding the existing `composer.json` file.

Ask confirmation before overriding composer.json

---

bin/dktl
src/Command/InitCommands.php
src/DrupalProjectTrait.php
tests/dktl_test.sh

If we're using running a CI pipeline, or doing local DKAN development, we want to be able to use an existing clone of the DKAN repo rather than simply pulling it in from packagist. 
This PR adds a `--dkan-local` switch to the `dktl init` command that will add a custom repository to your project composer.json. If you have a folder called "dkan" in your project root, it will symlink to that as your dkan dependency rather than pulling from packagist.
1. Create a new project dir ("localdkan")
2. `cd localdkan && git clone git@github.com:getdkan/dkan.git`
3. `dktl init --dkan-local`
4. `dktl make`
Confirm that when composer installs DKAN it outputs `Installing getdkan/dkan (2.x-dev): Symlinking from dkan` rather than `Downloading (100%)`
Just examine the test output of GetDKAN/dkan#3223 …

Add option for local DKAN

---

assets/docker/docker-compose.common.yml
composer.json
composer.lock
src/Command/DkanCommands.php

Some of DKAN's Cypress tests need to be run with chromium due to some memory issues with electron. To do this we need to allow dkan:test-cypress to accept options that can be passed to the cypress executable.
Also by default composer now installs version 2 which is breaking both dkan-tools and dkan. Even though this PR has failing tests, the prove that they will become green once these fixes and fixes in DKAN are merged can be seen here: https://github.com/GetDKAN/dkan/pull/3255

Allow dkan:test-cypress to accept cypress command options, and make dkan-tools compatible with composer 2

---

assets/site/development.services.yml

1. checkout this branch of dkan-tools
2. stand up a local dkan site with branch query-joins-v1
2. stand up a local app that makes a call to the dkan site.
3. Confirm that you get results and not a CORs error
To make data from your catalog available to 3rd party applications:
1. create a _services.yml_ file in a location under version control (src/site) with the following text:
```
cors.config:
enabled: true
allowedHeaders: ['*']
allowedMethods: ['*']
allowedOrigins: ['http://myappdomain.com']
exposedHeaders: false
maxAge: false
supportsCredentials: false
```
2. Add the domain for the App to the **allowedOrigins** array.
3. Update your settings.php file to include the following config to point to the services.yml file `$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/services.yml';`

fix development.services.yml

---

bin/dktl
tests/dktl_test.sh

Reverts GetDKAN/dkan-tools#273.
This was not a duplicate - perhaps code could be clearer but we need to move up two directories. `dirname` gives us the parent dir of the path we pass it.

Revert "Remove a duplicate code line"

---

src/Command/MakeCommands.php

Currently if composer fails (usually due to a constraint issue) during the make, this is not detected and the command continues and still exits successfully. Among other thigns this leads to confusing CI output and CI jobs continuing long after they should have quit. This will check for an exit code and fail if found.
See this demonstration: https://app.circleci.com/pipelines/github/GetDKAN/dkan/1078/workflows/28e1d40d-6a2a-4da9-ac8b-fe8ca932cd6c/jobs/13758

Fail the make command if composer exits with error

---

src/Command/InitCommands.php
src/Command/MakeCommands.php
src/DrupalProjectTrait.php
tests/dktl_test.sh

Instead of using then overriding the default drupal recommended composer project, we're going to start using a new [DKAN recommended project](https://packagist.org/packages/getdkan/recommended-project#9.x-dev).

Use new project and change some composer logic

---

src/Command/MakeCommands.php

Every time we run dktl make we get a deprecation notice because we use the --dev option with composer install. This PR simply offers the same functionality using the --no-dev option which will not be deprecated.

Use no-dev instead of dev with composer install.

---

bin/dktl

When running `dktl init` in a folder with only a vanilla dkan project instance, I received the following error:
```
No local dkan folder in project root.
```
It seems the logic used to determine the location of the current DKAN project was incorrect. It expected a "dktl.yml" file to be present in the current directory, or in some parent directory. It then noticed I had a stray "dktl.yml" file in my home directory and thought my home directory was the project directory.
I've updated the project directory detection logic to assume that the current directory is the project directory when `dktl init` or `dktl make` is called.
1. Create a directory containing only an empty "dktl.yml" file.
2. Create a subdirectory within that directory.
3. In the subdirectory, clone a copy of DKAN core into a …

Fix method for determining DKAN project directory

---

assets/docker/docker-compose.common.yml
assets/docker/etc/mysql/my.cnf

We are using [drydock](https://github.com/drydockcloud/drupal-acquia) under the hood for our CLI image, so we should switch to using it for our database image as well. This will more closely emulate the acquia environment.

Switch to drydock/percona database image

---

docs/testusers.md
mkdocs.yml
src/Command/DkanCommands.php
src/Command/ProjectCommands.php
src/Util/TestUserTrait.php
testUsers.json

This pr revamps the testing trait to create test users based on a testUsers.json file added to the root of the project/src folder. If there isn't a testUsers.json file in the project folder the testUsers.json file in the dktl root folder will be used.
The ProjectCommands.php was also updated to create the test users before cypress runs then delete the test users after cypress tests are completed.
There are also 2 new commands added if you want to create/delete test users without running cypress. They are:
`dkan:create-test-users` alias `qauc`
`dkan:delete-test-users` alias `qaud`

Adding ability to create test accounts using a file to the testing trait

---

src/Command/ProjectCommands.php

The project cypress commands were not returning anything, which means that pipelines are not likely to detect a test failure when using this command.

Return result from project:test-cypress

---

src/Command/DkanCommands.php

Previously we returned nothing so circleCI would not fail the build if phpunit failed.

Return actual status from dkan:test-phpunit

---

src/Command/FrontendCommands.php
src/Command/InitCommands.php
src/Util/TestUserTrait.php
tests/dktl_test.sh

Cypress tests are failing because the frontend:build is failing
```
npm run build
> @civicactions/data-catalog-app@1.0.3 build
> react-scripts build
Creating an optimized production build...
Failed to compile.
./src/theme/index.scss
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
```
Switching to a version of [data-catalog-app](https://github.com/GetDKAN/data-catalog-app/pull/105) that uses sass rather than node-sass, allows the build to complete
But--- then the tests fail due to this
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.
```
So adding the …

Specify project root for test user creation

---

src/Command/ProjectCommands.php
tests/dktl_test.sh

The current command assumes a particular testsuite name. This simply runs phpunit in the project root, assuming all is defined as needed in phpunit.xml or else passed as an option to the command.

Fixes some issues with project:test-phpunit
