bin/app.php
src/Commands/BasicCommands.php
src/Commands/DkanCommands.php
src/Commands/DockerCommands.php
src/Commands/DrupalCommands.php
src/Util/Util.php

Makes init create the appropriate structure

---

assets/docker/docker-compose.common.yml
composer.json
composer.lock
src/Command/DkanCommands.php
src/Util/Util.php

Connects #42
**QA**
Add this to your dktl.yml file:
```
"dkan:restore":
db_url: "s3://dkan-tools/last_install.sql"
files_url: "s3://dkan-tools/files.zip"
```
Run `dkan:restore`
A DKAN site should be the result.
**NOTE:** First, this will not work until GetDkan/dkan-docker#3 gets in. Also, aws has multiple mechanisms to authenticate. One of those must be working in your host machine for the container to be able to operate.

Adding the capability to handle s3 private resources.

---

src/Command/DkanCommands.php

After some of our most current changes, the extraction mechanism provided by Robo, which is the one use in the dkan:get command, stopped working well for us. This PR fixes the issue.
**QA**
- Try `dkan:get`
- You should be a version of DKAN

Changing the dkan:get mechanisms

---

assets/.circleci/config.yml
assets/.probo.yml
assets/settings.probo.php
src/Command/initCommands.php

*QA*
- `dktl init`
- Add the following to `dktl.yml`:
```
"dkan:get":
version: "7.x-1.15.3"
"dkan:restore":
db_url: "https://s3.amazonaws.com/dkan-tools/last_install.sql"
files_url: "https://s3.amazonaws.com/dkan-tools/files.zip"
```
- Grab .aws.tar.gz from `https://s3.console.aws.amazon.com/s3/object/dkan-tools/.aws.tar.gz?region=us-east-1&tab=overview`
- Decompress `.aws.tar.gz` and place in `~`
- Also, add `.aws.tar.gz` still compressed to the build assets in Probo.CI
- `dktl init:cicle-ci`
- `dktl init:probo-ci`
- `dktl dkan:get`
- `dktl dkan:make`
- `dktl drupal:make`
- `dktl drupal:remove-git-ignores`
- Add all of the files to your repo and push.
Connects #44

Command to generate basic configuration for CircleCI and ProboCI.

---

assets/.probo.yml
src/Command/DkanCommands.php

Setting sites/default and files permissions correctly.

---

bin/app.php
bin/dktl

This is temporary until there is a way to get this from the settings.

Add env for Drupal version

---

README.md

Some improvements to the docs structure to eliminate redundancy and improve readability.

Tighten up the docs

---

src/Drupal/V7/DrupalCommands.php
src/Drupal/V7/MakeCommands.php

Provide a "remove git files" command on the CLI but also available to make functions.

Consolodate git rm functionality

---

src/Drupal/V8/BasicCommands.php

Updates how interra is downloaded.

Interra update

---

bin/dktl

Load correct xdebug settings on macos

---

README.md
bin/dktl
src/Drupal/V7/InitCommands.php
src/Drupal/V7/TestCommands.php
src/Drupal/V7/TestingTrait.php
src/Util/TestingTrait.php
src/Util/Util.php

Adds two new dktl commands, dktl test:behat-custom and dktl test:phpunit-custom.
Connects #20

Support for custom tests

---

src/Drupal/V8/BasicCommands.php

Add a few extra options to `dltk make` which would be useful for deployment tasks. These are options that get passed to composer.

Add a few extra options to `dltk make`

---

src/Drupal/V8/BasicCommands.php

- checkout this branch on your local dkan-tools
- build a dkan2 site from scratch
- confirm you have the GetDKAN/data-catalog-frontend (0.0.1)

Switch frontend

---

src/Drupal/V8/BasicCommands.php

Relative symlinks should work inside and outside Docker

---

src/Drupal/V7/MakeCommands.php

The `--yes` option was broken on D7 make. Also made some code style fixes.

Fix -y option on make commands

---

src/Drupal/V8/BasicCommands.php

- Add symlink for config
- Remove deprecated bower-asset symlink 
- Change 'error' to 'warning' to be less alarming

update drupal 8 basic commands

---

.codeclimate.yml
assets/d8/site/settings.docker.php
assets/d8/site/settings.php
assets/settings.probo.php
assets/site/settings.docker.php
assets/site/settings.php
assets/test/phpunit/example/CustomTest.php
bin/app.php
src/Command/BasicCommands.php
src/Command/InitCommands.php
src/Command/RestoreCommands.php
src/Drupal/V7/BasicCommands.php
src/Drupal/V7/DkanCommands.php
src/Drupal/V7/DrupalCommands.php
src/Drupal/V7/MakeCommands.php
src/Drupal/V7/TestCommands.php
src/Drupal/V8/BasicCommands.php
src/Drupal/V8/DkanCommands.php
src/Drupal/V8/DrupalCommands.php
src/Drupal/V8/InitCommands.php
src/Util/TestingTrait.php
src/Util/Util.php
tests/DktlV7Test.php
tests/DktlV8Test.php

Automatic and manual fixes using PHPCS and PSR-12 standard.

Apply PSR coding standards

---

README.md

Moving site upgrade and maintenance info from the catalog docs to here

update README with additional maintenance info

---

src/Command/InstallCommands.php

Reverts GetDKAN/dkan-tools#205

Revert "Update install commands to use new module names"

---

assets/docker/docker-compose.common.yml
src/BasicCommands.php
tests/DktlTest.php

Switch web's image to @rhabbachi 's dkan-web in order to get PHP 7.3

Switch web's image to dkan-web

---

src/Command/InstallCommands.php

Issue: https://github.com/GetDKAN/dkan-tools/issues/221

The standard profile already enables dblog

---

assets/d8/site/settings.docker.php
assets/docker/docker-compose.common.yml
bin/dktl
src/Command/InitCommands.php

+ Fix file_public_base_url setting.
+ Better handling of dktl-proxy startup. Delete any eventual previous instance if any.
+ Quote bash script variables.

Misc Fixes and Improvements

---

bin/dktl

Bash script is very hard to parse visually. This breaks it up into functions and (hopefully) makes it easier to follow the program flow.
1. Check out branch locally.
2. Try to build a new project from scratch, confirm basic functions are working.
Note: We should confirm exit codes are still correct, let's discuss further

Refactor bash script for better readibility/maintainability

---

README.md
assets/docker/etc/php5/php.ini
bin/dktl
src/Command/DockerCommands.php
src/Command/FrontendCommands.php
src/Command/InitCommands.php
src/Command/RestoreCommands.php
src/Command/XdebugCommands.php
src/DrupalProjectTrait.php

Fix some typos

---

src/Command/DkanCommands.php

- `dktl init --dkan=2.x-dev`
- `dktl dev`
- confirm that you can checkout dkan branches at: _docroot/modules/contrib/dkan_
- confirm that you can checkout app branches at: _src/frontend_

add dkan:dev command

---

assets/site/development.services.yml
assets/site/settings.docker.php
src/Command/InitCommands.php

Drupal adds additional check on POST query
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
Fixes GetDKAN/dkan#3258

Add development.services.yml to assets

---

src/Command/InstallCommands.php

Not sure but think this helps with errors on drush upon install in pipelines.

Change drush to dktl in installCommands

---

assets/docker/docker-compose.common.yml

Update docker-compose.common.yml to pull php74-based image.

Update dkan-cli to php74 image

---

src/Command/ProjectCommands.php

Adds namespace declaration for `Util`.

332: Add proper namespace declaration for Util class
